spring:
  application:
    name: LimitChecker
  jpa:
    properties:
      hibernate:
        show_sql: true

limit:
  default-currency: USD
  default-sum: 1000

client:
  twelve-data-api:
    url: https://api.twelvedata.com/time_series
    api-key: ${TWELVE_DATA_API_KEY}
    interval: 1day